extends: airbnb-base

env:
  browser: true
  node: true
  mocha: true

parserOptions:
  ecmaVersion: 2018
  sourceType: script

rules:
  'comma-dangle': ['error', 'never']
  'strict': ['error', 'global']
  'max-len': ['error', { code: 120 }]
  'no-trailing-spaces': ['error', { skipBlankLines: true }]
  'object-curly-newline': ['error', { consistent: true }]
  'no-console': 'error'