language: node_js

node_js:
  - '13'
  - '12'
  - '10'

script:
  - npm run lint
  - npm run coverage

jobs:
  include:
    - stage: Release to NPM
      if: branch = master
      deploy:
        provider: npm
        email: $NPM_AUTH_EMAIL
        api_key: $NPM_AUTH_TOKEN
        access: public
        edge: true
        cleanup: false
